config/routes.rb
Rails.application.routes.draw do
  resources :rails
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "products#index"
  resources :products do
    resources :categories
  end
  resources :categories
end

app/models/category.rb
class Category < ApplicationRecord
  # Associations
  has_many :categorized_products, dependent: :destroy
  has_many :products, through: :categorized_products

  # Validations
  validates :name, presence: true, uniqueness: true

  # implement a nested category structure with the `ancestry` gem
  # has_ancestry
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_path, status: :see_other, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.expect(category: [ :name, :description ])
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= category.description %>
  </p>

  <h3>Products in this category:</h3>
  <ul>
    <% category.products.each do |product| %>
      <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>
</div>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<% content_for :title, "Editing category" %>

<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Categories" %>

<h1>Categories</h1>

<%= link_to "New category", new_category_path %>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Actions</th>
    <th>Products</th>
  </tr>
  </thead>
  <tbody>
  <% @categories.each do |category| %>
    <tr>
      <td><%= category.name %></td>
      <td><%= category.description %></td>
      <td><%= link_to "Show", category %></td>
      <td>
        <% category.products.each do |product| %>
          <%= link_to product.name, product %><br>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/categories/new.html.erb
<% content_for :title, "New category" %>

<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>